### ISSUE TITLE
Wallet details not showing

### ISSUE THREAD

**Issue by ZabadyManga** [hubiinetwork/hubii-core#552]
Using the latest release v0.5.1 the wallet details aren't shown with the message "Synchronising..." for ever, seems similar to #538

**Comment by ZabadyManga** [comment]
Hey Liam,

Thanks for the quick response, I tried already before the application restart but it didn't help, I enbled the console log and it seems the app keep try fetching balances about my added addresses all the time

![image](https://user-images.githubusercontent.com/43371649/45685221-fce97d80-bb48-11e8-9ea1-624761c79bc5.png)

**Comment by ZabadyManga** [comment]
Not sure though if this is what you are looking for :)

**Comment by liamaharon** [comment]
That's exactly what I was looking for :) 

It looks like requests to the hubii API are working, meaning the issue is likely with requests to our Ethereum nodes. To try to narrow down the issue to either your PC or your network, are you able to try using your current computer on a different network (eg mobile hotspot) or a different computer on your current network?

**Comment by liamaharon** [comment]
Great to hear it's working now :smiley: 
 
We plan on integrating a 'Network status' indicator in the future which will help with debugging these kinds of issues, thanks for bearing with us during these early stages
