### ISSUE TITLE
Displayed value of HBT is much lower than current price

### ISSUE THREAD

**Issue by chris-kgs** [hubiinetwork/hubii-core#594]
The displayed value of HBT within the wallets section of core is only around 5-10% of what it should be valued at based on coinmarketcap or exchange prices.  As FYI the value was correct when I first imported the wallet.

**Comment by liamaharon** [comment]
Thanks for reporting this, the price seems to be consistent with coinmarketcap now. The problem you described likely occurred due to low liquidity of HBT causing pricing differences across different exchanges, meaning there is no single source of truth for the price. I expect incidents like these to become exceedingly rare as HBT gains liquidity.

**Comment by imakemoney87** [comment]
I just imported a wallet containing hubii into hubii core but unfortunately, the price displayed is significantly lower than it should be.
The displayed balance would equal a hbt price of 0.013 usd (1.3 usd cent). However, the amount of HBT is displayed correctly. 
Current price at coinmarketcap.com is above 0.17 usd. 
Can that really be explained by low liquidity and pricing differences across exchanges?

**Comment by ZabadyManga** [comment]
I was looking for this issue to add the same comment, the price displayed for HBT is not actually matching the one on CMC currently. Even looking at the prices per exchange on CMC "IDEX/FD" still the displayed price is ways lower.

**Comment by chris-kgs** [comment]
I've been tracking this the last couple of weeks.  This issue seems to appear only when there is zero 24-hour volume on IDEX.

**Comment by liamaharon** [comment]
Bug will be fixed shortly up-stream on our backend
