### ISSUE TITLE
Support custom derivation paths, and a Ledger Live derivation path option

### ISSUE THREAD

**Issue by vidarhaha** [hubiinetwork/hubii-core#595]
I have a created two ethereum accounts with two different root derivation paths on my Ledger Nano S. My idea was to have one with my ether and one with my Hubits. Maybe not necessary, but some funds already transferred. 

Would it be an idea to be able to edit the root deviation path, like in MEW. They have an option where you can edit the path instead of choosing the default m/44'/60'/0'/0.

**Comment by liamaharon** [comment]
Thanks for the suggestion @vidarhaha, this is on our todo :+1:

**Comment by vidarhaha** [comment]
Maybe choose m/44'/60'/1'/0/0 as the initial value on an editable option, since I assume that would be the most common option, next after the default derivation path. And maybe an explanatory clickable text button marked with "i" for information.

Hubii core is very user-friendly, and more options would of course complicate the solution for the end user. Would be better if users didn't have to figure out root derivation paths on the Ledger, but I guess that is more difficult. Here is a relevant discussion: [Ledger now use BIP44 for accounts address derivation](https://github.com/MyCryptoHQ/MyCrypto/issues/2070#issue-341249164). 

Keep up the good work!

**Comment by liamaharon** [comment]
Thanks for sharing that link. I wasn't aware the Ledger Live team decided to adopt BIP44, that definitely bumps the priority of this issue. I think we can aim to include it in v0.7.0, scheduled for release next week.

As gre pointed out, a custom path isn't the best solution for Ledger Live wallets:
>Basically you can use the "Custom field" and manually input: m/44'/60'/0'/0 then select the first derived address (this is LedgerLive first account), then switch to m/44'/60'/1'/0, select the first address (this is LedgerLive second account), and so on..

As well as allowing users to specify a custom path, ideally we would also add a 3rd preset derivation path `Ledger (Ledger Live)` that iterates over `x` in `m/44'/60'/x'/0/0`. This would allow users to view all of their Ledger Live derived addresses at once, a feature surprisingly not yet supported by either MEW or MyCrypto. 

To reduce confusion, we can rename the existing `Ledger (ETH)` option to something like `Ledger (MyCrypto, MyEtherWallet, Ledger Chrome App)`.

@katat let me know if this sounds OK to you, I'm happy to work on this to include in the 0.7.0 release. Here's a list of changes I think are required:
- Only fetch addresses & balances for the 'page' of addresses the user is currently viewing (10 at a time)
- Allow viewing 100 pages of addresses instead of the current 2
- Support deriving addresses using a 'hardened' path
- Add a 
    `m/44'/60'/[index]'/0/0`
    `Ledger (Ledger Live)` 
     option to the derivation path container
- Change `Ledger (ETH)` --> `Ledger (MyCrypto, MyEtherWallet, Ledger Chrome App)`
- Add `/[index]` to the end of the existing paths here
![screenshot from 2018-11-06 14-03-10](https://user-images.githubusercontent.com/16665596/48040371-bc16f800-e1cc-11e8-8624-d200b01a915e.png)

**Comment by katat** [comment]
@liamaharon Make senses to me. Yes, let's include this change in the 0.7
