### ISSUE TITLE
cant withdraw

### ISSUE THREAD

**Issue by ValKos** [hubiinetwork/hubii-core#755]
Tried to withdraw 100 NII, but failed, H.core says:
![изображение](https://user-images.githubusercontent.com/30324699/56687343-bb244500-66de-11e9-924c-094ce804f0ed.png)
Have plenty of NII on the balance. What's the problem?

P.S. It would be great to collect pop-up messages in the statusbar below, or at least in log file.

**Comment by katat** [comment]
Hi @ValKos, thanks for raising up this issue.
From what I see in the screenshot, it is probably due to the setting in your Ledger Nano S device. The withdrawal process will require interacting with the smart contracts, so it needs to turn on the contract support on your LNS device. Please try the following on your LNS:

1. Open the ETH app.
2. Go to "Setting".
3. Go to "Contract data" and set it to "Yes"

Then you should be able to start the withdrawal/settlement process with your LNS. Let us know if you still experience any issues after these steps.

**Comment by ValKos** [comment]
Thank you @katat . It was indeed the case. Works perfectly.
